### PR TITLE
Added contrast filter and fade alpha randomization

### PR DESCRIPTION
**Pull request by Dguto9**
Adds contrast filter and fading randomization for the wallpaper. It had to be done in an odd way due to the fact that the updates were made in an unrelated repository rather than a fork.

### CODE REVIEW

**Comment by Dguto9** [comment]
I can instead try this again but updating the current js and html manually in the fork instead of replacing the html and js with my modified ones.

**Comment by drelatgithub** [comment]
Thank you so much!

> I can instead try this again but updating the current js and html manually in the fork instead of replacing the html and js with my modified ones.

Yeah, that is the main reason why PR is preferred, such that the changes can be tracked locally without changing the whole file. But for sure let me know if you have any questions!

**Comment by Dguto9** [comment]
I will go ahead and make a new fork and manually add the couple changes, that way the merge is less messy. Should I make a new pull request for that or edit this one?

**Comment by drelatgithub** [comment]
A new PR might be needed. I will keep this open for now just in case!

**Pull request closed without merging**
